### ISSUE TITLE
Dormant db resources reused when postgres resource is edited with anything.

### ISSUE THREAD

**Issue by the-redback** [kubedb/operator#121]
Dormant database resources are reused when postgres resource, with the same name, is edited with anything. And, after reusing, the object of the Dormant database was not deleted.

Say there is a dormant database, p1. 

I have created this dormantdb by these steps,
```console
$ kubedb create -f https://raw.githubusercontent.com/k8sdb/cli/master/docs/examples/postgres/demo-1.yaml
validating "https://raw.githubusercontent.com/k8sdb/cli/master/docs/examples/postgres/demo-1.yaml"
postgres "p1" created

$ kubectl get pods -n demo
NAME                       READY     STATUS    RESTARTS   AGE
p1-0                       1/1       Running   0          11s
pgadmin-3504868301-dd1r6   1/1       Running   0          2h


$ kubedb edit pg p1 -n demo
postgres "p1" edited

$ kubedb delete pg -n demo p1
postgres "p1" deleted


$ kubectl get pods -n demo
NAME                       READY     STATUS        RESTARTS   AGE
p1-0                       1/1       Terminating   0          1m
pgadmin-3504868301-dd1r6   1/1       Running       0          2h


$ kubedb get drmn -n demo
NAME      STATUS    AGE
p1        Paused    1m
```
Now, if we create a new postgres object with the same yaml file we used before, the process will fail because the spec of the new object contains (spec.doNotPause: true) which conflicts with dormant database. But The problem is if we edit this new p1 object with anything (say, doNotPause: false, or storage: 51Mi), the operator creates a statefulSet reusing the resources of dormantDb p1 and the dormant db object was not deleted. The Next steps are:

```console
$ kubedb create -f https://raw.githubusercontent.com/k8sdb/cli/master/docs/examples/postgres/demo-1.yaml
validating "https://raw.githubusercontent.com/k8sdb/cli/master/docs/examples/postgres/demo-1.yaml"
postgres "p1" created

$ kubedb get pg -n demo
NAME      STATUS    AGE
p1        Failed    24s


$ kubedb get drmn -n demo
NAME      STATUS    AGE
p1        Paused    2m


$ kubedb edit pg p1 -n demo
postgres "p1" edited


$ kubectl get pods -n demo
NAME                       READY     STATUS    RESTARTS   AGE
p1-0                       1/1       Running   0          4s
pgadmin-3504868301-dd1r6   1/1       Running   0          2h


$ kubedb get drmn -n demo
NAME      STATUS    AGE
p1        Paused    3m
```

The bugs I faced:
i. The dormant db object should be deleted when a statefulSet is created using its resources. 
ii. The operator creates a statefulSet when it encounters an edit to postgres object, without checking dormant database object specs.

**Comment by tamalsaha** [comment]
This issue was moved to kubedb/project#32
