### ISSUE TITLE
If docker.CheckDockerImageVersion fails, send an event to analytics

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/operator#59]

**Comment by aerokite** [comment]
When you are creating a database, controller validates its version. If it fails to validate, it will push an event.
```
  1m          1m         1         Postgres operator   Warning    Failed               Fail to be ready Postgres: "postgres-demo". Reason: Image kubedb/postgres:9.6-db not found
  1m          1m         1         Postgres operator   Warning    Invalid              Image kubedb/postgres:9.6-db not found
```

But at the very beginning, when controller is starting, It checks some Images whose versions are pass in flags. If operator fails to validate, It will not move forward. It gives error with `log.Fatalf`

**Comment by TamalSaha** [comment]
> But at the very beginning, when controller is starting, It checks some Images whose versions are provided as flags. If operator fails to validate, It will not move forward. It gives error with log.Fatalf because operator will not actually work properly

That sounds good. But we should still collect analytics for these events.

**Comment by tamalsaha** [comment]
This issue was moved to kubedb/project#72
